### ISSUE TITLE
Veritrans.load_config cannot render erb lines.

### ISSUE THREAD

**Issue by gizipp** [veritrans/veritrans-ruby#21]
Hi @Paxa,

I have veritrans.yml with enviroment variable like this :

```
production:
  client_key: <%= ENV['VERITRANS_CLIENT_KEY'] %>
  server_key: <%= ENV['VERITRANS_SERVER_KEY'] %>
  api_host: <%= ENV['VERITRANS_API_HOST'] %>
```

I got error message when charge.

```
Aug 16 15:05:33 ip-10-0-108-87 KarirApp: URI::InvalidURIError (bad URI(is not URI?): <%= ENV['VERITRANS_API_HOST'] %>/v2/charge):
Aug 16 15:05:33 ip-10-0-108-87 KarirApp:     /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb:176:in `split'
Aug 16 15:05:33 ip-10-0-108-87 KarirApp:     /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
Aug 16 15:05:33 ip-10-0-108-87 KarirApp:     /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
Aug 16 15:05:33 ip-10-0-108-87 KarirApp:     /home/ubuntu/.gem/ruby/2.1.5/gems/veritrans-2.0.4/lib/veritrans/client.rb:78:in `make_request'
Aug 16 15:05:33 ip-10-0-108-87 KarirApp:     /home/ubuntu/.gem/ruby/2.1.5/gems/veritrans-2.0.4/lib/veritrans/client.rb:35:in `request_with_logging'
Aug 16 15:05:33 ip-10-0-108-87 KarirApp:     /home/ubuntu/.gem/ruby/2.1.5/gems/veritrans-2.0.4/lib/veritrans/api.rb:46:in `charge'
```
I found out `Veritrans.load_config` cannot load erb lines. When I looked up `Veritrans.config`, they are still in raw.

```
Loading production environment (Rails 4.2.5.1)
irb(main):001:0> Veritrans.config
=> <Veritrans::Config @api_host="<%= ENV['VERITRANS_API_HOST'] %>" @server_key="<%= ENV['VERITRANS_SERVER_KEY'] %>" @client_key="ENV['VERITRANS_CLIENT_KEY']" @http_options=nil>
```

**Comment by Paxa** [comment]
Thank you for your contribution
